const cv = {
    name: 'robin mikaelsen-cunningham',
    about: 'Software developer with a passion for patterns, process and knowledge exchange. Key interests in accessibility, performance optimisation and clean code. Skilled communicator looking for their next challenge with an organisation that is as excited as they are to foster and develop new talents.',
    experience: [
        {
            id: 1,
            companyName: 'thinkmoney',
            title: 'Professional Software Developer',
            employmentType: 'Full-time',
            isCurrent: true,
            start: '2021-02',
            end: '',
            description: ''
        },
        {
            id: 2,
            companyName: 'thinkmoney',
            title: 'Foundation Software Developer',
            employmentType: 'Full-time',
            isCurrent: false,
            start: '2018-10',
            end: '2021-02',
            description: 'Full stack development role writing, releasing and maintaining services in strongly DevOps orientated environment. Regularly host agile ceremonies, contribute a technical perspective to refinements, pair with developers of mixed experiences and conduct code reviews. Expected to have experience across the in-use stack as well as being a knowledge base for specific business and technology areas. With legacy and digital transformation platforms being written from a full stack perspective knowledge sharing is a key component to the role and culture at thinkmoney. Katas, presentations and documentation are used to facilitate knowledge sharing and growth of the team.'
        },
        {
            id: 3,
            companyName: 'northcoders',
            title: 'Trainee Developer',
            employmentType: '',
            isCurrent: false,
            start: '2018-02',
            end: '2018-07',
            description: 'An intensive 24-week Manchester based bootcamp. Developed full-stack programming skills through a range of projects focusing on Javascript, NodeJS and React. Practical, industry-responsive curriculum, curated to in still an enthusiasm for learning new technologies in an adaptive environment. All code was TDD and utilised version control (Git), with frequent pair programming. Delivered 2 end-to-end applications, the first, Northcoders News, a result of two set sprints and the other, Northcoders Final Project, using kanban methodologies. As part of the graduation ceremony I presented my application and the ideas that fuelled the development process.'
        },
        {
            id: 4,
            companyName: 'vf dalston / lyall hakaraia',
            title: 'Creative Media Assistant',
            employmentType: 'Freelance',
            isCurrent: false,
            start: '2016-08',
            end: '2019-11',
            description: 'Redesigned the organisation’s website vfdalston.com using Squarespace and CSS. Using the same technological stack and a similar process, I remotely delivered lyallhakaraia.com, a website for the director of vf dalston, lyall hakaraia. '
        },
    ],
    pronouns: 'they/them',
    contact: [
        {
            id: 1,
            type: 'email',
            display: 'robin.jmc@icloud.com',
            link: 'robin.jmc@icloud.com'
        }
    ],
    portfolio: [
        {
            id: 1,
            type: 'link',
            display: 'github',
            link: 'https://github.com/robinjmc'
        },
        {
            id: 2,
            type: 'link',
            display: 'robin mikaelsen-cunningham',
            link: 'http://localhost:3000/'
        },
    ],
    skills: [
        {
            id: 1,
            name: 'Current Professional Stack',
            content: 'CSS, HTML, React, Gatsby, Outsystems, Jest, CI/CD, container and storage based AWS services, terraform, azure devops, octopus, datadog, SQL, Go, C#, Objective-C, Java'
        },
        {
            id: 2,
            name: 'Current Professional Methodologies',
            content: 'agile, sprint delivery, CI/CD, TDD, BDD, SOLID principles, BEM'
        }
    ],
    education: [{
        id: 1,
        schoolName: 'Goldsmiths, University of London',
        degreeName: 'BMus Popular Music',
        grade: '2:1',
        description: 'Specialised in technology and its role in performance.',
        activitiesAndSocieties: ['Wired Radio', 'Goldsmiths Vocal Ensemble', 'Goldsmiths Bass Society', 'Goldsmiths Basketball'],
        start: '2012-09',
        end: '2015-06'
    }],
    other: {
        title: 'hobbies / interests',
        description: 'Keen interest in local & diy art and music scenes with a sense of humour. I occasionally perform ‘music’ generated by computers and improvised input (e.g. most recently I popped balloons for 25 minutes). Love a long walk, either in real life or big open world video games.'
    }
}
export default cv;